project:
  title: "GIS Portfolio"
  output-dir: _site/en

website:
  site-url: https://cdbyl.github.io/portfolio
  description: "Carolina Byl's Portfolio"
  favicon: loguito.png
  open-graph:
    locale: en_US
  twitter-card:
    creator: "@cdbyl"
  navbar:
    left:
      - text: "Home"
        href: index.html
      - text: "Projects"
        href: projects.html
      #- text: "Blog"
      #  href: blog.html
      #- icon: rss
      #  href: blog.xml
    right:
      - text: "Espa√±ol"
        href: ../es/
  page-footer:
    left: "Site created with Quarto"

lang: en


