project:
  title: "Portfolio SIG"
  output-dir: ./_site/es

website:
  site-url: https://cdbyl.github.io/portfolio
  description: "Portfolio de Carolina Byl"
  favicon: loguito.png
  open-graph:
    locale: es_ES
  twitter-card:
    creator: "@cdbyl"
  navbar:
    left:
      - text: "Inicio"
        href: index.html
      - text: "Proyectos"
        href: projects-es.html
      #- text: "Blog"
      #  href: blog.html
      #- icon: rss
      #  href: blog.xml
    # right:
    #   - text: "English"
    #     href: ./_site/en
    #   - text: "Espa√±ol"
    #     href: ./_site/es
  page-footer:
    left: "Sitio creado con Quarto"

lang: es

